### ISSUE TITLE
[Bug Report] `view-image-tools` visibility

### ISSUE THREAD

**Issue by eallion** [Tokinx/ViewImage#5]
If there is a large image with a white background, the `view-image-tools` is invisible, because of its background-color.

Pic sample:
![FixclxAUUAAxJoX](https://user-images.githubusercontent.com/1698841/204756558-1c1e8ed8-22de-4dde-9448-0df8699a9e7d.png)

**Comment by Tokinx** [comment]
Thanks a lot, I will optimize the CSS style for `view-image-tools`

**Comment by Tokinx** [comment]
fixed:https://github.com/Tokinx/ViewImage/commit/e435dcb9455c604a38f4bd1c11d8e135548cf1e2

**Comment by eallion** [comment]
Thanks!
